//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietSachDaiLyLay
    {
        public int id { get; set; }
        public int idDL { get; set; }
        public int idSach { get; set; }
        public System.DateTime ngayLay { get; set; }
        public Nullable<int> soLuongXuat { get; set; }
    
        public virtual Sach Sach { get; set; }
        public virtual DaiLy DaiLy { get; set; }
    }
}
