//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHoaDonBan
    {
        public int idCTHDB { get; set; }
        public int idHDB { get; set; }
        public int idSach { get; set; }
        public int idLV { get; set; }
        public Nullable<int> soLuong { get; set; }
    
        public virtual HoaDonBan HoaDonBan { get; set; }
        public virtual LinhVuc LinhVuc { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
