//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonBan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDonBan()
        {
            this.CTHoaDonBans = new HashSet<CTHoaDonBan>();
        }
    
        public int idHDB { get; set; }
        public int idDL { get; set; }
        public string diaChi { get; set; }
        public string sDT { get; set; }
        public Nullable<System.DateTime> ngayBan { get; set; }
        public string nguoiNhanSach { get; set; }
        public string tongTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHoaDonBan> CTHoaDonBans { get; set; }
        public virtual DaiLy DaiLy { get; set; }
    }
}
